- name: Install Nginx on webservers 1 2 3
  hosts: pvt
  gather_facts: yes
  become: yes
  become_user: root
  tasks:
  - name: Perform Apt update
    shell: apt update

  - name: Install nginx webserver
    shell: apt install -y nginx
    tags:
    - nginx_install
  - name: Start nginx webserver
    shell: service nginx start 
  tags:
  - nginx
  
- name: InstallSupport tools
  hosts: pub
  become: yes
  become_user: root
  tasks:
  - name: InstallSupport tools
    shell: apt install -y net-tools jq tree unzip
    tags:
    - tools_install
  tags:
  - tools